apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: test-app
  template:
    metadata:
      labels:
        app: test-app
    spec:
      containers:
        - name: test-app
          image: python:3.11-slim
          command: ["/bin/sh", "-c", "python /app/server.py"]
          env:
            - name: PORT
              value: "8080"
            - name: MIN_ITERATIONS
              value: "250000"
            - name: MAX_ITERATIONS
              value: "750000"
            - name: MAX_SLEEP_SECONDS
              value: "0.2"
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu:  500m
              memory: 256Mi
            limits:
              cpu: "2"
              memory: 512Mi
          volumeMounts:
            - name: test-app-server
              mountPath: /app/server.py
              subPath: server.py
      volumes:
        - name: test-app-server
          configMap:
            name: test-app-server

---
apiVersion: v1
kind: Service
metadata:
  name: test-app
spec:
  selector:
    app: test-app
  ports:
    - name: http
      port: 80
      targetPort: 8080
