---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-hpa-plus-v1alpha1-hpaplus
  failurePolicy: Fail
  name: mhpaplus.kb.io
  rules:
  - apiGroups:
    - hpa.plus
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - hpapluses
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-hpa-plus-v1alpha1-hpaplus
  failurePolicy: Fail
  name: vhpaplus.kb.io
  rules:
  - apiGroups:
    - hpa.plus
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - hpapluses
  sideEffects: None
