---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: hpa-plus-operator
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
- apiGroups:
  - ""
  resources:
  - replicationcontrollers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - replicationcontrollers/scale
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - apps
  resources:
  - deployments
  - replicasets
  - statefulsets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - deployments/scale
  - replicasets/scale
  - statefulsets/scale
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - custom.metrics.k8s.io
  - external.metrics.k8s.io
  - metrics.k8s.io
  resources:
  - '*'
  verbs:
  - get
  - list
- apiGroups:
  - hpa.plus
  resources:
  - hpapluses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - hpa.plus
  resources:
  - hpapluses/finalizers
  verbs:
  - update
- apiGroups:
  - hpa.plus
  resources:
  - hpapluses/status
  verbs:
  - get
  - patch
  - update
