apiVersion: jamiethompson.me/v1alpha1
kind: PredictiveHorizontalPodAutoscaler
metadata:
  name: test-xgboost-scaler
spec:
  syncPeriod: 15000
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: test-app
  minReplicas: 1
  maxReplicas: 20
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 0
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
  models:
    - type: XGBoost
      name: cpu-predictor
      xgboost:
        historySize: 400
        lookAhead: 60000 # ~4 syncs ahead
        lags: 8
        windowSize: 8
        nEstimators: 400
        maxDepth: 5
        learningRate: 0.05
        subsample: 0.8
        colsampleBytree: 0.8
  decisionType: mean
